// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfuqaajaqvgoliiytutg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdXFhYWphcXZnb2xpaXl0dXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzQ4OTAsImV4cCI6MjA1NzExMDg5MH0.65goro4__jyJ9JtJJDDNAQSX6cP4xEKM7Or8ekz5izU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);