
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Clean install dependencies
        run: |
          echo "Removing existing node_modules and package-lock.json..."
          rm -rf node_modules package-lock.json
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed successfully"
        
      - name: Build application
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed successfully"
        env:
          NODE_ENV: production
          
      - name: Verify build output
        run: |
          echo "Build verification:"
          echo "- Checking dist directory exists..."
          [ -d "dist" ] && echo "✓ dist directory exists" || (echo "✗ dist directory missing" && exit 1)
          
          echo "- Checking index.html exists..."
          [ -f "dist/index.html" ] && echo "✓ index.html exists" || (echo "✗ index.html missing" && exit 1)
          
          echo "- Checking assets directory..."
          [ -d "dist/assets" ] && echo "✓ assets directory exists" || (echo "✗ assets directory missing" && exit 1)
          
          echo "- Listing build contents:"
          find dist -type f | head -20
          
          echo "- Checking asset references in index.html:"
          if [ -f "dist/index.html" ]; then
            grep -o 'href="[^"]*"' dist/index.html || echo "No href attributes found"
            grep -o 'src="[^"]*"' dist/index.html || echo "No src attributes found"
          fi
          
          echo "- Asset files count: $(find dist/assets -type f 2>/dev/null | wc -l)"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
